PANEL:
  DEVICE:
    WIDTH: 540
    HEIGHT: 960
    DPI: 100.0
  UPDATE:
    INTERVAL: 60

INFLUXDB:
  URL: http://proxy.green-rabbit.net:8086
  TOKEN: fffjkjkgfklhjglkjiojtroijojhkljhklghklfjklhhlnklhnklfgnhklgnhgfdlhfgnhlkngdfnfnhgdkfnh==
  ORG: home
  BUCKET: sensor

SENSOR:
  HOSTNAME: rasp-aqua
  TYPE: rasp

GRAPH:
  PARAM_LIST:
    - NAME: temp
      TITLE: Temperature
      FORMAT: "{:.1f}"
      UNIT: Celsius
      YTICKS:
        MIN: 23
        MAX: 28.1
        STEP: 2
      NORMAL:
        MIN: 23.5
        MAX: 27.5

    - NAME: ph
      TITLE: pH
      FORMAT: "{:.2f}"
      UNIT: pH
      YTICKS:
        MIN: 6.0
        MAX: 7.6
        STEP: 0.5
      NORMAL:
        MIN: 6.2
        MAX: 7.5

    - NAME: tds
      TITLE: Total Dissolved Solids
      FORMAT: "{:.0f}"
      UNIT: ppm
      YTICKS:
        MIN: 300
        MAX: 700
        STEP: 100
      NORMAL:
        MIN: 100
        MAX: 500

    - NAME: flow
      TITLE: Water flow
      FORMAT: "{:.2f}"
      UNIT: "L/min"
      YTICKS:
        MIN: 0
        MAX: 4.5
        STEP: 1
      NORMAL:
        MIN: 1.5
        MAX: 10

FONT:
  PATH: ./font/ # スクリプトのフォルダからの相対パス
  MAP:
    EN_MEDIUM: OptimaLTStd-Medium.otf
    EN_BOLD: OptimaLTStd-Bold.otf

LIVENESS:
  FILE: /dev/shm/healthz
  INTERVAL: 300
